version = 0.1

[o-49cf1bc1-dev]
[o-49cf1bc1-dev.deploy]
[o-49cf1bc1-dev.deploy.parameters]
aws_account_number = "360520317360"
stack_name = "o-49cf1bc1-dev"
s3_prefix = "o-49cf1bc1-dev"
region = "eu-central-1"
confirm_changeset = false
capabilities = "CAPABILITY_IAM CAPABILITY_AUTO_EXPAND CAPABILITY_NAMED_IAM"
disable_rollback = false

[o-49cf1bc1-prod]
[o-49cf1bc1-prod.deploy]
[o-49cf1bc1-prod.deploy.parameters]
aws_account_number = "360520317360"
stack_name = "o-49cf1bc1-prod"
s3_prefix = "o-49cf1bc1-prod"
region = "eu-central-1"
confirm_changeset = false
capabilities = "CAPABILITY_IAM CAPABILITY_AUTO_EXPAND CAPABILITY_NAMED_IAM"
disable_rollback = false